name: Release
on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        target: [x86_64-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: |
          zig build -Doptimize=ReleaseSafe -Dstrip -Dcpu=baseline -Dtarget=${{ matrix.target }}

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release update ${{ github.ref }} zig-out/bin/dipm-${{ matrix.target }}
